class AppStrings {
  // English
  static const Map<String, String> en = {
    'app_title': 'Digital Library',
    'borrow': 'Borrow',
    'return': 'Return',
    'add_book': 'Add Book',
    'student_name': 'Student Name',
    'student_grade': 'Student Grade',
    'book_title': 'Book Title',
    'author': 'Author',
    'isbn': 'ISBN',
    'category': 'Category',
    'scan_qr': 'Scan QR Code',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'success': 'Success',
    'error': 'Error',
    'enter_details': 'Please enter all required details',
    'scan_book': 'Scan the book QR code',
    'processing': 'Processing...',
    'language': 'Language',
    'book_id': 'Book ID',
    'logged_console': 'Data logged to console',
    'scan_successful': 'Scan Successful',
    'scanned_code': 'Scanned code:',
    'scan_again': 'Scan Again',
    'confirm': 'Confirm',
    'settings': 'Settings',
    'server_settings': 'Server Settings',
    'server_ip_address': 'Server IP Address',
    'save': 'Save',
    'settings_saved': 'Settings saved successfully',
    'invalid_ip': 'Invalid IP address format',
    'connection_error': 'Connection Error',
    'connection_error_message': 'Unable to connect to the server. Please check your internet connection and ensure the server IP address is configured correctly.',
    'go_to_settings': 'Go to Settings',
    'try_again': 'Try Again',
  };

  // Bahasa Indonesia
  static const Map<String, String> id = {
    'app_title': 'Perpustakaan Digital',
    'borrow': 'Pinjam',
    'return': 'Kembali',
    'add_book': 'Tambah Buku',
    'student_name': 'Nama Siswa',
    'student_grade': 'Kelas',
    'book_title': 'Judul Buku',
    'author': 'Penulis',
    'isbn': 'ISBN',
    'category': 'Kategori',
    'scan_qr': 'Pindai Kode QR',
    'submit': 'Kirim',
    'cancel': 'Batal',
    'success': 'Berhasil',
    'error': 'Kesalahan',
    'enter_details': 'Mohon masukkan semua detail yang diperlukan',
    'scan_book': 'Pindai kode QR buku',
    'processing': 'Memproses...',
    'language': 'Bahasa',
    'book_id': 'ID Buku',
    'logged_console': 'Data tercatat di konsol',
    'scan_successful': 'Pemindaian Berhasil',
    'scanned_code': 'Kode yang dipindai:',
    'scan_again': 'Pindai Lagi',
    'confirm': 'Konfirmasi',
    'settings': 'Pengaturan',
    'server_settings': 'Pengaturan Server',
    'server_ip_address': 'Alamat IP Server',
    'save': 'Simpan',
    'settings_saved': 'Pengaturan berhasil disimpan',
    'invalid_ip': 'Format alamat IP tidak valid',
    'connection_error': 'Kesalahan Koneksi',
    'connection_error_message': 'Tidak dapat terhubung ke server. Silakan periksa koneksi internet Anda dan pastikan alamat IP server dikonfigurasi dengan benar.',
    'go_to_settings': 'Ke Pengaturan',
    'try_again': 'Coba Lagi',
  };

  // Prevent instantiation
  AppStrings._();
}
